name: base_env
channels:
- conda-forge
- bioconda
- defaults
dependencies:
- pandas==2.1.3
- python-box==7.1.1
- pathlib==1.0.1
- snakemake==7.32.4
- r-base==4.3.2
- r-openxlsx==4.2.5.2
- r-stringr==1.5.1
- r-yaml==2.3.7
- bioconductor-chipqc==1.36.0
- bioconductor-txdb.hsapiens.ucsc.hg38.knowngene==3.17.0
- r-data.table==1.14.8
- r-rmarkdown==2.25
- pandoc==2.5
- gsutil==5.26
- awscli==2.13.25
- openssl==3.1.3