## INITIALIZE
genome:
    fa: "Homo_sapiens.ensembl.version110.genome.fa"
    bwt: "Homo_sapiens.ensembl.version110.genome.fa.bwt"
annot:
    gtf: "Homo_sapiens.ensembl.version110.chr.gtf"


## INGEST
input:
    input_fastq: "{{sample}}_{read}.fastq.gz"
cutadapt:
    cutadapt_fastq: "{{sample}}_{read}"
rqual_filter:
    qfilter_fastq_single: "{{sample}}_{read}_qual.fastq.gz"
    qfilter_fastq_paired: "{{sample}}_{read}{paired}_qual.fastq.gz"


## MAPPING
bam:
    bam: "{sample}.bam"
    index: "{sample}.bam.bai"

rseqc:
    bamqc_txt: "{sample}_bam_qc.txt"
    bamgc_txt: "{sample}_bam_gc.txt"
    bamgc_r: "{sample}.GC_plot.r"

fastqc:
    targz: "{sample}_fastqc.tar.gz"


## ANALYSIS
cnv:
    bed: "{sample}_cnv.bed"

peak:
    xls: "{sample}_peaks.xls"
    peak_narrow: "{sample}_peaks.narrowPeak"
    peak_broad: "{sample}_peaks.broadPeak"
    extra_narrow: "{sample}_summits.bed"
    extra_broad: "{sample}_peaks.gappedPeak"

chipqc:
    csv: "{sample}_chipqc.csv"


## DOWNSTREAM ANALYSIS ## TODO
#ceas:
#    csv: "{sample}_peak_annot.csv"
#gene_target:
#    csv: "{sample}_gene_target.csv"
#motif:
#    csv: "{sample}_homer.csv"
#conservation:
#    csv: "{sample}_conserv.csv"


## REPORT ## TODO
#report:
#    html: "{submissionID}_cidc_atac_report.html"
#    fig:
#    tab:

