## workflow info
srcdir: '/media/scratch/cherikhsr/cidc_atac/source'
predir: '/media/scratch/cherikhsr/atac_test_output'
datadir: '/media/scratch/cherikhsr/atac_test_output/analysis/data'
repdir: '/media/scratch/cherikhsr/atac_test_output/analysis/report'
log_file: '/media/scratch/cherikhsr/atac_test_output/preprocess.log'
ncores: 16
subdirs: benchmark log info progress genome annot input


## output file paths layout file
file_layout: '/media/scratch/cherikhsr/cidc_atac/config/file_layout.yaml'


## reference genome download locations file
reference: '/media/scratch/cherikhsr/cidc_atac/config/reference.csv'


## sample metadata file
sample_metadata: '/media/scratch/cherikhsr/cidc_atac/config/sample_metadata.csv'


## preprocess options
quality_trim: '20'


## peak calling options
peak_mode: 'narrow'
ext_size: '150'
shift: '-75'
peak_fdr: '0.01'


## genome track region option TODO input bedfile to plot multiple tracks if needed
track_region: 'chr1:750000-1050000'


## cloud program [gsutil, aws]
cloud_prog: gsutil


## cloud info for pulling input files / pushing results TODO remove encryption ones
archive_bucket: ''
